version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  backend:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/finance
      - JWT_SECRET=supersecretjwt
    depends_on:
      - db
    ports:
      - "4000:4000"
volumes:
  db_data:
